@host = localhost:5000

###

# @name sheets
GET http://{{host}}/sheets

###

@id = {{sheets.response.body.sheets[0].id}}

GET http://{{host}}/sheet/{{id}}

###

POST http://{{host}}/refresh

###

GET http://{{host}}/spec



