name: Package
on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel poetry
      - name: Build package
        run: |
          poetry build
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: python_packages
          path: dist/*
          retention-days: 1
          overwrite: true

  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel pytest
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: python_packages
          path: dist
      - name: Install package
        run: |
          python -m pip install dist/*.whl
      - name: Test package
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
